version: "3"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - .:/app
        depends_on:
            - db
    web:
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        ports:
            - 8080:80
        volumes:
            - .:/app
        depends_on:
            - app
    db:
        image: mysql:8.4
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
